###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

    {
        "email": "pepa@gmail.com",
        "password": "Abcd1234"
    }

###
GET http://localhost:3000/api/users

###
DELETE http://localhost:3000/api/users/pepe@gmail.com

###
PUT http://localhost:3000/api/users/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5OGU2NTMxZmU1MjExYTViZGIwYTkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzM1OTg0MCwiZXhwIjoxNzQzMzY3MDQwfQ.49nGRBbwslRU4Vqs_2BjqWhg3836nO2088QmFRC5Doc

{
    "code": 230484
}

###
POST http://localhost:3000/mail
Content-Type: application/json

    {
        "subject": "prueba",
        "text": "esto es una prueba",
        "to": "agathamartinv@gmail.com",
        "from": "agathamartinv@gmail.com"

    }

